### ISSUE TITLE
Solve encryption issue in pdf to text conversion

### ISSUE THREAD

**Issue by mbaddar1** [mbaddar1/llm-flow#46]
[ERROR]	2023-06-26T11:46:53.096Z	9e97d635-660c-4566-935f-05077f3b92ee	Exception PyCryptodome is required for AES algorithm
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 82, in lambda_handler
    text = get_text_from_pdf(io.BytesIO(input_bytes))
  File "/var/task/lambda_function.py", line 33, in get_text_from_pdf
    pdfreader = PyPDF2.PdfReader(input_stream)
  File "/opt/python/PyPDF2/_reader.py", line 339, in __init__
    self._encryption.verify(pwd) == PasswordType.NOT_DECRYPTED
  File "/opt/python/PyPDF2/_encryption.py", line 785, in verify
    key, rc = self.verify_v4(pwd) if self.algV <= 4 else self.verify_v5(pwd)
  File "/opt/python/PyPDF2/_encryption.py", line 836, in verify_v5
    key = AlgV5.verify_owner_password(
  File "/opt/python/PyPDF2/_encryption.py", line 530, in verify_owner_password
    AlgV5.calculate_hash(R, password, o_value[32:40], u_value[:48])
  File "/opt/python/PyPDF2/_encryption.py", line 561, in calculate_hash
    E = AES_CBC_encrypt(K[:16], K[16:32], K1 * 64)
  File "/opt/python/PyPDF2/_encryption.py", line 162, in AES_CBC_encrypt
    raise DependencyError("PyCryptodome is required for AES algorithm")
PyPDF2.errors.DependencyError: PyCryptodome is required for AES algorithm

possible solutions
https://stackoverflow.com/questions/73701005/pypdf2-error-pycryptodome-is-required-for-aes-algorithm

input-file
[Q1_2022_e.pdf](https://github.com/mbaddar1/llm-flow/files/11868370/Q1_2022_e.pdf)

**Comment by mbaddar1** [comment]
DONE

**lambda** 
arn:aws:lambda:eu-north-1:963535522076:function:build_vectordb_index
**test file**
s3://uploadeddatallm/v7lswZjoGBFOtooTHGciTMrCku8dwRPeCQH2qFUONBdtKVSUsfYo964RrWHr7QPbjQ4enuepGC4AxomSlkzJBxI56dBXXrulARaJYCuLEt2FfFEWdkC8tAWQju8LZQ1I/EN_Geschäftsbericht 2022_VW FS AG_IFRS_final.pdf

**test event**

{
  "Records": [
    {
      "eventVersion": "2.0",
      "eventSource": "aws:s3",
      "awsRegion": "us-east-1",
      "eventTime": "1970-01-01T00:00:00.000Z",
      "eventName": "ObjectCreated:Put",
      "userIdentity": {
        "principalId": "EXAMPLE"
      },
      "requestParameters": {
        "sourceIPAddress": "127.0.0.1"
      },
      "responseElements": {
        "x-amz-request-id": "EXAMPLE123456789",
        "x-amz-id-2": "EXAMPLE123/5678abcdefghijklambdaisawesome/mnopqrstuvwxyzABCDEFGH"
      },
      "s3": {
        "s3SchemaVersion": "1.0",
        "configurationId": "testConfigRule",
        "bucket": {
          "name": "uploadeddatallm",
          "ownerIdentity": {
            "principalId": "EXAMPLE"
          },
          "arn": "arn:aws:s3:::example-bucket"
        },
        "object": {
          "key": "v7lswZjoGBFOtooTHGciTMrCku8dwRPeCQH2qFUONBdtKVSUsfYo964RrWHr7QPbjQ4enuepGC4AxomSlkzJBxI56dBXXrulARaJYCuLEt2FfFEWdkC8tAWQju8LZQ1I/EN_Geschäftsbericht 2022_VW FS AG_IFRS_final.pdf",
          "size": 1024,
          "eTag": "0123456789abcdef0123456789abcdef",
          "sequencer": "0A1B2C3D4E5F678901"
        }
      }
    }
  ]
}

**log**

Test Event Name
s3test1

Response
{
  "status": "200",
  "body": "s3://llm-index/v7lswZjoGBFOtooTHGciTMrCku8dwRPeCQH2qFUONBdtKVSUsfYo964RrWHr7QPbjQ4enuepGC4AxomSlkzJBxI56dBXXrulARaJYCuLEt2FfFEWdkC8tAWQju8LZQ1I/EN_Geschäftsbericht 2022_VW FS AG_IFRS_final"
}

Function Logs
is longer than the specified 1000
[WARNING]	2023-06-26T13:59:48.655Z	687c9709-c90d-44f7-b9f4-10fbcccfc9ab	Created a chunk of size 2049, which is longer than the specified 1000
[WARNING]	2023-06-26T13:59:48.655Z	687c9709-c90d-44f7-b9f4-10fbcccfc9ab	Created a chunk of size 1334, which is longer than the specified 1000
[WARNING]	2023-06-26T13:59:48.655Z	687c9709-c90d-44f7-b9f4-10fbcccfc9ab	Created a chunk of size 1500, which is longer than the specified 1000
[WARNING]	2023-06-26T13:59:48.655Z	687c9709-c90d-44f7-b9f4-10fbcccfc9ab	Created a chunk of size 1361, which is longer than the specified 1000
[WARNING]	2023-06-26T13:59:48.655Z	687c9709-c90d-44f7-b9f4-10fbcccfc9ab	Created a chunk of size 1177, which is longer than the specified 1000
[WARNING]	2023-06-26T13:59:48.655Z	687c9709-c90d-44f7-b9f4-10fbcccfc9ab	Created a chunk of size 1342, which is longer than the specified 1000
[WARNING]	2023-06-26T13:59:48.655Z	687c9709-c90d-44f7-b9f4-10fbcccfc9ab	Created a chunk of size 1259, which is longer than the specified 1000
[WARNING]	2023-06-26T13:59:48.656Z	687c9709-c90d-44f7-b9f4-10fbcccfc9ab	Created a chunk of size 1542, which is longer than the specified 1000
[WARNING]	2023-06-26T13:59:48.656Z	687c9709-c90d-44f7-b9f4-10fbcccfc9ab	Created a chunk of size 1084, which is longer than the specified 1000
[WARNING]	2023-06-26T13:59:48.656Z	687c9709-c90d-44f7-b9f4-10fbcccfc9ab	Created a chunk of size 1905, which is longer than the specified 1000
[WARNING]	2023-06-26T13:59:48.656Z	687c9709-c90d-44f7-b9f4-10fbcccfc9ab	Created a chunk of size 2032, which is longer than the specified 1000
[WARNING]	2023-06-26T13:59:48.656Z	687c9709-c90d-44f7-b9f4-10fbcccfc9ab	Created a chunk of size 1356, which is longer than the specified 1000
[WARNING]	2023-06-26T13:59:48.656Z	687c9709-c90d-44f7-b9f4-10fbcccfc9ab	Created a chunk of size 1141, which is longer than the specified 1000
[WARNING]	2023-06-26T13:59:48.656Z	687c9709-c90d-44f7-b9f4-10fbcccfc9ab	Created a chunk of size 1271, which is longer than the specified 1000
[WARNING]	2023-06-26T13:59:48.656Z	687c9709-c90d-44f7-b9f4-10fbcccfc9ab	Created a chunk of size 1340, which is longer than the specified 1000
[WARNING]	2023-06-26T13:59:48.656Z	687c9709-c90d-44f7-b9f4-10fbcccfc9ab	Created a chunk of size 1413, which is longer than the specified 1000
[WARNING]	2023-06-26T13:59:48.656Z	687c9709-c90d-44f7-b9f4-10fbcccfc9ab	Created a chunk of size 1746, which is longer than the specified 1000
[WARNING]	2023-06-26T13:59:48.656Z	687c9709-c90d-44f7-b9f4-10fbcccfc9ab	Created a chunk of size 1705, which is longer than the specified 1000
[WARNING]	2023-06-26T13:59:48.656Z	687c9709-c90d-44f7-b9f4-10fbcccfc9ab	Created a chunk of size 1196, which is longer than the specified 1000
[WARNING]	2023-06-26T13:59:48.656Z	687c9709-c90d-44f7-b9f4-10fbcccfc9ab	Created a chunk of size 1184, which is longer than the specified 1000
[WARNING]	2023-06-26T13:59:48.656Z	687c9709-c90d-44f7-b9f4-10fbcccfc9ab	Created a chunk of size 3011, which is longer than the specified 1000
[INFO]	2023-06-26T14:00:00.227Z	687c9709-c90d-44f7-b9f4-10fbcccfc9ab	Loading faiss with AVX2 support.
[INFO]	2023-06-26T14:00:00.391Z	687c9709-c90d-44f7-b9f4-10fbcccfc9ab	Successfully loaded faiss with AVX2 support.
[INFO]	2023-06-26T14:00:00.589Z	687c9709-c90d-44f7-b9f4-10fbcccfc9ab	vector store successfully created
[INFO]	2023-06-26T14:00:00.610Z	687c9709-c90d-44f7-b9f4-10fbcccfc9ab	successfully saved the index locally to files : /tmp/EN_Geschäftsbericht 2022_VW FS AG_IFRS_final with extensions .pkl and .faiss
[INFO]	2023-06-26T14:00:01.009Z	687c9709-c90d-44f7-b9f4-10fbcccfc9ab	Successfully uploaded the local index file to s3://llm-index/v7lswZjoGBFOtooTHGciTMrCku8dwRPeCQH2qFUONBdtKVSUsfYo964RrWHr7QPbjQ4enuepGC4AxomSlkzJBxI56dBXXrulARaJYCuLEt2FfFEWdkC8tAWQju8LZQ1I/EN_Geschäftsbericht 2022_VW FS AG_IFRS_final with extensions .pkl and .faiss
END RequestId: 687c9709-c90d-44f7-b9f4-10fbcccfc9ab
REPORT RequestId: 687c9709-c90d-44f7-b9f4-10fbcccfc9ab	Duration: 53407.09 ms	Billed Duration: 53408 ms	Memory Size: 512 MB	Max Memory Used: 443 MB	Init Duration: 2611.71 ms

Request ID
687c9709-c90d-44f7-b9f4-10fbcccfc9ab

**output**

s3://llm-index/v7lswZjoGBFOtooTHGciTMrCku8dwRPeCQH2qFUONBdtKVSUsfYo964RrWHr7QPbjQ4enuepGC4AxomSlkzJBxI56dBXXrulARaJYCuLEt2FfFEWdkC8tAWQju8LZQ1I/EN_Geschäftsbericht 2022_VW FS AG_IFRS_final.faiss


s3://llm-index/v7lswZjoGBFOtooTHGciTMrCku8dwRPeCQH2qFUONBdtKVSUsfYo964RrWHr7QPbjQ4enuepGC4AxomSlkzJBxI56dBXXrulARaJYCuLEt2FfFEWdkC8tAWQju8LZQ1I/EN_Geschäftsbericht 2022_VW FS AG_IFRS_final.pkl

s3://llm-index/v7lswZjoGBFOtooTHGciTMrCku8dwRPeCQH2qFUONBdtKVSUsfYo964RrWHr7QPbjQ4enuepGC4AxomSlkzJBxI56dBXXrulARaJYCuLEt2FfFEWdkC8tAWQju8LZQ1I/EN_Geschäftsbericht 2022_VW FS AG_IFRS_final.txt
